# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 491054154a351c09de18e7093f258f72c9eb393371786eafa58988be213dbbe2b4e61c579ed79fbd4e635973044ff53aff600c1dec9ba829431fcb3141d7ccb7

test:
  secret_key_base: 6bbac097aa3c690ac4be6f95a81a49f3d17373f1babbc9c45a3918fab37043b06a0ac7cea0ab1fa79a5a4850efa9d0e31ebf1091503184212de66d6c7ddd06cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
